# Site settings
title: Zhuxu's Blog
name: FIXME # your name
email: 332525966@qq.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zhuxu1.github.io" # the base hostname & protocol for your site
twitter_username: zhuxu1 # your Twitter username
github_username: zhuxu1 # your Github username
disqus_username: zhuxu1 # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: on # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
